apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-ca-certs
  namespace: {{ .Values.namespace }}
data:
  Trust-Root-CA.crt: |-
{{ .Values.trustCaRoot | nindent 4 }}
  Forward-Trust-CA-ECDSA.pem.crt: |-
{{ .Values.forwardTrustCaEcdsa | nindent 4 }}
  Forward-Trust-CA.pem.crt: |-
{{ .Values.forwardTrustCa | nindent 4 }}