apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-ca-certs
  namespace: {{ .Values.namespace.app }}
data:
  Trust-Root-CA.crt: |-
{{ .Files.Get "../../../ca/Trust-Root-CA.crt" | nindent 4 }}
  Forward-Trust-CA-ECDSA.pem.crt: |-
{{ .Files.Get "../../../ca/Forward-Trust-CA-ECDSA.pem.crt" | nindent 4 }}
  Forward-Trust-CA.pem.crt: |-
{{ .Files.Get "../../../ca/Forward-Trust-CA.pem.crt" | nindent 4 }}