# values.yaml
namespace:
  app: ai-app
  ingress: ingress-nginx

podrole: arn:aws:iam::12345678:role/ks-pod-role

ui:
  replicaCount: 1
  image:
    repository: migara/ui-app
    pullPolicy: Always
    tag: latest
  service:
    port: 80
    targetPort: 3000
  serviceAccountName: eks-pods-sa

agent:
  replicaCount: 1
  image:
    repository: migara/agent-app
    pullPolicy: Always
    tag: latest
  service:
    port: 80
    targetPort: 3001
  serviceAccountName: eks-pods-sa

ingress:
  enabled: true
  className: nginx
  proxyReadTimeout: "3600"
  proxySendTimeout: "3600"
  paths:
    - path: /api/
      pathType: Prefix
      serviceName: agent-service
      servicePort: 80
    - path: /
      pathType: Prefix
      serviceName: ui-service
      servicePort: 80
