# values.yaml
namespace:
  app: utilities

podrole: arn:aws:iam::12345678:role/ks-pod-role

# Values for netshoot.yaml
netshoot:
  deploymentName: netshoot-deployment
  replicas: 1
  image: nicolaka/netshoot
  serviceAccountName: eks-pods-sa
  customCertsConfigMap: custom-ca-certs