---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: eks-pods-sa
  namespace: ai-app
  annotations:
    eks.amazonaws.com/role-arn: ${role_arn}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: eks-pods-sa
  namespace: kube-system
  annotations:
    eks.amazonaws.com/role-arn: ${role_arn}
