apiVersion: v1
kind: Service
metadata:
  name: pan-ngfw-svc
  namespace: {{ .Values.namespace }}
  labels:
    app: pan-ngfw-svc
spec:
  ports:
    - protocol: UDP
      port: 6080
      targetPort: 6080
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: pan-ngfw-svc-endpoints
  namespace: {{ .Values.namespace }}
  labels:
    kubernetes.io/service-name: pan-ngfw-svc
addressType: IPv4
ports:
  - name: ''
    protocol: UDP
    port: 6080
endpoints:
  # Endpoints can be added or removed based on requirements and zone availability.
  - addresses:
      - {{ .Values.endpoints1 }}
    zone: {{ .Values.endpoints1zone }}
    hints:
      forZones:
        - name: "{{ .Values.endpoints1zone }}"
  - addresses:
      - {{ .Values.endpoints2 }}
    zone: {{ .Values.endpoints2zone }}
    hints:
      forZones:
        - name: "{{ .Values.endpoints2zone }}"
