apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-ca-certs
  namespace: ai-app
data:
  Forward-Trust-CA-ECDSA.pem.crt: |-
    ${indent(4, forward_trust_ca_ecdsa)}
  Forward-Trust-CA.pem.crt: |-
    ${indent(4, forward_trust_ca)}
