apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-cli-deployment
  namespace: ai-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aws-cli
  template:
    metadata:
      labels:
        app: aws-cli
    spec:
      serviceAccountName: eks-pods-sa
      containers:
      - name: aws-cli
        image: amazon/aws-cli
        env:
        - name: AWS_CA_BUNDLE
          value: "/etc/pki/ca-trust/source/anchors/Trust-Root-CA.crt"
        command:
          - /bin/bash
        args:
          - -c
          - |
            yum install -y ca-certificates
            cp /custom-certs/* /etc/pki/ca-trust/source/anchors/
            update-ca-trust
            echo "Custom certificates added"
            sleep infinity
        volumeMounts:
        - name: custom-certs
          mountPath: /custom-certs
          readOnly: true
      volumes:
      - name: custom-certs
        configMap:
          name: custom-ca-certs