---
apiVersion: v1
kind: Namespace
metadata:
  name: migara-app
---
apiVersion: v1
kind: Service
metadata:
  name: ui-service
  namespace: migara-app
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
    service.beta.kubernetes.io/aws-load-balancer-subnets: "${lb_subnet_ids}"
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: ui
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-deployment
  namespace: migara-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
        - name: ui
          image: migara/ui-app
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: agent-service
  namespace: migara-app
spec:
  type: ClusterIP
  ports:
    - port: 3001
      targetPort: 3001
  selector:
    app: agent
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent-deployment
  namespace: migara-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agent
  template:
    metadata:
      labels:
        app: agent
    spec:
      containers:
        - name: agent
          image: migara/agent-app
          ports:
            - containerPort: 3001
