apiVersion: apps/v1
kind: Deployment
metadata:
  name: netshoot-deployment
  namespace: ai-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netshoot
  template:
    metadata:
      labels:
        app: netshoot
    spec:
      serviceAccountName: "${service_account_name}"
      containers:
      - name: netshoot
        image: nicolaka/netshoot
        command: ["/bin/sh"]
        args:
        - -c
        - |
          cp /custom-certs/* /usr/local/share/ca-certificates/
          update-ca-certificates
          echo "Custom certificates added"
          while true; do sleep 3600; done
        volumeMounts:
        - name: custom-certs
          mountPath: /custom-certs
          readOnly: true
      volumes:
      - name: custom-certs
        configMap:
          name: custom-ca-certs