apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent-deployment
  namespace: {{ .Values.namespace.app }}
spec:
  replicas: {{ .Values.agent.replicaCount }}
  selector:
    matchLabels:
      app: agent
  template:
    metadata:
      labels:
        app: agent
    spec:
      serviceAccountName: {{ .Values.agent.serviceAccountName }}
      containers:
        - name: agent
          image: "{{ .Values.agent.image.repository }}:{{ .Values.agent.image.tag }}"
          imagePullPolicy: {{ .Values.agent.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.agent.service.targetPort }}
