apiVersion: v1
kind: Service
metadata:
  name: agent-service
  namespace: {{ .Values.namespace.app }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.agent.service.port }}
      targetPort: {{ .Values.agent.service.targetPort }}
  selector:
    app: agent