apiVersion: v1
kind: Service
metadata:
  name: ui-service
  namespace: {{ .Values.namespace.app }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.ui.service.port }}
      targetPort: {{ .Values.ui.service.targetPort }}
  selector:
    app: ui